<defaults>
/ fontstyle = ("Arial", 3%, false, false, false, false, 5, 0)
/ screencolor = black
/ txbgcolor = black
/ txcolor = white
</defaults>

<values>
/  trialcount = 3
</values>

<text Ttext>
/ items = ("count = <% values.trialcount %>")
</text>

<trial Ttrial>
/ ontrialbegin = [values.trialcount = trial.Ttrial.count;]
/ stimulustimes = [500=Ttext]
/ validresponse = (" ")
</trial>

<block tblock>
/ trials = [1,2=Ttrial]
</block>

