<defaults>
/ fontstyle = ("Arial", 3%, false, false, false, false, 5, 0)
/ screencolor = black
/ txbgcolor = black
/ txcolor = white
</defaults>

<counter C1>
/ items = (1,1,2,2)
/ select = noreplace
/ selectionrate = always
</counter>

<counter C2>
/ items = (1,1,2,2)
/ select = sequence
/ selectionrate = always
</counter>

<page P>
noreplace = <% counter.C1.selectionmode %>
sequence = <% counter.C2.selectionmode %>
</page>

<block T>
/ preinstructions = (P)
</block>

